### ISSUE TITLE
List devices

### ISSUE THREAD

**Issue by ingemar** [jonomuller/device-volume-adjuster#1]
Hi!

How do you know the devices' names? 

There should be an option `-l` to list devices.

**Comment by felix021** [comment]
You'll see the list by clicking on the sound button (volume button).

Another approach could be `brew install switchaudio-osx`, and run `SwitchAudioSource -a | grep output`. Just don't forget to remove the trailing "(output)".

**Comment by ingemar** [comment]
Thank you!
